Добавляет адаптивные сетки
htmlacademy-adaptive/2069371-cat-energy-27 pull request #4
Opened 2023-01-10 16:26 UTC by M1haan

2023-01-12 15:03 UTC, Dima-Dim requested changes

2023-01-12 15:03 UTC, Dima-Dim commented on source/sass/advantages.scss
> +@media (min-width: $tablet-width) {
Не нужно так делать. Это усложняет понимание того, какой селектор как меняется. Используй медиавыражения внутри каждого из селекторов, для которого они нужны.

2023-01-12 15:03 UTC, Dima-Dim commented on source/sass/application-comment.scss
> +  @media (min-width: $tablet-width) {
Вот как здесь.

2023-01-12 15:03 UTC, Dima-Dim commented on source/sass/application-main.scss
> +.application__group {
Тут либо опечатка, либо это другой блок.

2023-01-12 15:03 UTC, Dima-Dim commented on source/sass/example.scss
> +    .example__slider-image {
https://up.htmlacademy.ru/adaptive/27/criteries#d11

2023-01-17 13:58 UTC, Dima-Dim requested changes
В опубликованной версии не загружается img/mp.jpg
img/hero-product.png используется для планшетной версии, хотя оно для неё явно маловато. Оно же используется и для десктопа.

2023-01-17 16:16 UTC, M1haan commented
Исправил карту и блок Hero, также заметил, что на странице каталога у изображений товаров не правильные размеры, но это исправлял уже в 5-ом домашнем задании

2023-01-22 18:15 UTC, closed without merging